# Generated by Django 4.2.3 on 2023-07-04 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                default=False,
                validators=[
                    django.core.validators.MaxValueValidator(
                        0, message="Number should be maximum 4 digits."
                    ),
                    django.core.validators.MinValueValidator(
                        100, message="Number should be minimum 0."
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.IntegerField(
                default=False,
                validators=[
                    django.core.validators.MaxValueValidator(
                        2023, message="Number should be maximum 4 digits."
                    ),
                    django.core.validators.MinValueValidator(
                        1900, message="Number should be minimum 0."
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="visibility",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
