# Generated by Django 4.2.3 on 2023-07-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_customuser_age_customuser_dob_customuser_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("visibility", models.BooleanField(default=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=8)),
                ("year_published", models.IntegerField()),
                ("file", models.FileField(upload_to="uploaded_files/")),
            ],
        ),
    ]
