# Generated by Django 4.2.3 on 2023-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="username",
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
