# Generated by Django 4.2.3 on 2023-07-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_uploadedfile_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
