# Generated by Django 4.2.3 on 2023-07-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="username",
        ),
    ]
