# Generated by Django 4.2.3 on 2023-07-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_uploadedfile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
