# Generated by Django 4.2.3 on 2023-07-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0009_customuser_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
    ]
