# Generated by Django 4.2.3 on 2023-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0010_remove_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(default=False),
            preserve_default=False,
        ),
    ]
