# Generated by Django 4.2.3 on 2023-07-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0011_customuser_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="token",
        ),
    ]
